# Generated by Django 5.0.1 on 2024-02-05 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_user_address_user_avatar_user_birthdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='birthDate',
            new_name='birth_date',
        ),
    ]
