# Generated by Django 5.0.1 on 2024-02-05 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_studyclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultLearning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('midterm_score', models.FloatField()),
                ('final_score', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
