# Generated by Django 5.0.1 on 2024-02-05 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_resultlearning_is_draft_resultlearning_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name_column', models.CharField(max_length=50)),
                ('score', models.FloatField()),
                ('result_learning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.resultlearning')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
