# Generated by Django 5.0.1 on 2024-02-05 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_scorecolumn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semester',
            old_name='school_year',
            new_name='schoolyear',
        ),
    ]
