# Generated by Django 5.0.1 on 2024-02-05 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_rename_school_year_semester_schoolyear'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semester',
            old_name='schoolyear',
            new_name='school_year',
        ),
    ]
