# Generated by Django 5.0.1 on 2024-02-20 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_course_image'),
    ]

    operations = [
    ]
