# Generated by Django 5.0.1 on 2024-02-21 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_mmigateforpythonanywhere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='resultlearning',
            name='study_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resultlearning_as_studyClass', to='myapp.studyclass'),
        ),
        migrations.AlterField(
            model_name='scorecolumn',
            name='result_learning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_columns', to='myapp.resultlearning'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/%Y/%m'),
        ),
    ]
