# Generated by Django 5.0.1 on 2024-02-22 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_alter_course_image_alter_resultlearning_study_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='class_study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_as_studyclass', to='myapp.studyclass'),
        ),
    ]
