# Generated by Django 5.0.1 on 2024-02-24 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_alter_post_class_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyclass',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms_as_semester', to='myapp.semester'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
    ]
